//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by coolplayer.rc
//
#define IDB_MAINUP                      101
#define IDD_PLAYLIST                    108
#define APP_ICON                        110
#define IDR_MENU1                       111
#define IDR_ACCELERATOR1                114
#define IDB_MAINSMALLFONT               115
#define IDB_MAINBIGFONT                 116
#define IDD_ABOUT                       118
#define IDR_ABOUT1                      125
#define IDD_OPTIONS                     126
#define IDI_ICON_MP3                    128
#define IDI_ICON_PLS                    129
#define IDD_TAGEDIT                     130
#define IDD_URL                         131
#define IDB_MAINDOWN                    132
#define IDR_KEYBOARD                    149
#define IDB_SYSTRAYBG                   152
#define IDB_SYSTRAYFG                   153
#define IDR_USAGE                       154
#define IDR_CHANGES                     156
#define IDB_PLAYLIST_CURRENTTRACK       157
#define IDD_QUICKFIND                   158
#define IDR_DEFAULTSKIN                 192
#define IDB_SYSICON                     194
#define IDB_SYSICON_MASK                196
#define IDC_PLAYLIST                    1000
#define IDC_OPENLIST                    1001
#define IDC_SAVELIST                    1002
#define IDC_CLEAR                       1003
#define IDC_MOVEUP                      1004
#define IDC_MOVEDOWN                    1005
#define IDC_SORTTEXT                    1006
#define IDC_MOVETEXT                    1007
#define IDC_CLEARSEL                    1008
#define IDC_SHUFFLE                     1010
#define IDC_ABOUTICON                   1012
#define IDC_ADDDIR                      1013
#define IDC_ABOUTTEXT                   1013
#define IDC_SPIN1                       1014
#define IDC_ARTIST                      1014
#define IDC_FIND                        1014
#define IDC_ALBUM                       1015
#define IDC_YEAR                        1016
#define IDC_COMMENT                     1017
#define IDC_ONTOP                       1018
#define IDC_TRACK                       1018
#define IDC_REGFILETYPE                 1019
#define IDC_ADDICONS                    1020
#define IDC_OUTPUT                      1026
#define IDC_MIXER                       1027
#define IDC_AUTOEXIT                    1029
#define IDC_REMEMBERPLS                 1030
#define IDC_WEBSITE                     1031
#define IDC_REMAINING                   1031
#define IDC_READTAG                     1032
#define IDC_GENRE                       1032
#define IDC_EXTENSIONS                  1033
#define IDC_EASYMOVE                    1034
#define IDC_MP3LIST                     1035
#define IDC_ROTATE                      1035
#define IDWRITE                         1036
#define IDC_SCROLLTITLE                 1036
#define IDC_URL                         1037
#define IDC_REMSONG                     1037
#define IDC_FILEONCE                    1038
#define IDC_LOADSKIN                    1039
#define IDC_READSELTAG                  1040
#define IDC_PLAYLISTSKIN                1041
#define IDC_SUPPORTID3_V2               1041
#define IDC_SKINBUTTON                  1042
#define IDC_PLAYLISTSKINBUTTON          1043
#define IDC_READID3INBACKGROUND         1043
#define IDC_AUTOPLAY                    1044
#define IDC_TASKBAR                     1045
#define IDC_MULTIPLEINSTANCES           1046
#define IDC_ABOUTRADIO                  1047
#define IDC_READTRACKTIME               1047
#define IDC_KEYBOARDRADIO               1048
#define IDC_PREFERNATIVEOGGTAGS         1048
#define IDC_REMEMBERSKIN                1049
#define IDC_CHANGELOG                   1049
#define IDC_REMSKINVAL                  1050
#define IDC_FLUSH_SKINLIST              1051
#define IDC_MINIMIZE                    1052
#define IDC_DELAYTIME                   1052
#define IDC_MAXIMIZE                    1053
#define IDC_PLAYERSKINCHECK             1053
#define IDC_CLOSE                       1054
#define IDC_PLAYLISTSKINCHECK           1054
#define IDC_DELAYTIMES                  1055
#define IDC_FND_TEXT                    1057
#define IDC_QFND_TITLES                 1058
#define IDC_QFND_ALBUMS                 1059
#define IDC_QFND_ARTISTS                1060
#define IDC_RADIO1                      1061
#define IDC_URL_STATIC                  1062
#define IDC_URL_ICON                    1063
#define IDC_URL_DESCRIPTION             1064
#define MENU_SKIN_DEFAULT               5000
#define MENU_OPENFILE                   40001
#define MENU_OPENLOC                    40002
#define MENU_PLAYLIST                   40003
#define MENU_OPTIONS                    40004
#define MENU_ABOUT                      40005
#define MENU_EXIT                       40006
#define ID_DELETE                       40007
#define ID_REPEAT                       40008
#define ID_SHUFFLE                      40009
#define ID_PLAY                         40010
#define ID_STOP                         40011
#define ID_PAUSE                        40012
#define ID_LOAD                         40013
#define ID_NEXT                         40014
#define ID_PREVIOUS                     40015
#define ID_VOLUMEUP                     40016
#define ID_VOLUMEDOWN                   40017
#define ID_SEEKFORWARD                  40022
#define ID_SEEKBACKWARD                 40023
#define ID_ABOUT                        40024
#define ID_PLAYLIST                     40026
#define ID_DRAWSKINLINES                40027
#define ID_LOADSKIN                     40028
#define ID_EQUALIZER                    40033
#define ID_EXIT                         40035
#define ID_FIND                         40036
#define MENU_ADDFILE                    40039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        197
#define _APS_NEXT_COMMAND_VALUE         40040
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
